CONFIG = {'encoder_name': 'UniFieldEncoder',
 'encoder_kwargs': {'embed_dims': (64, 128, 256, 512),
                    'depths': (4, 4, 4, 4),
                    'num_heads': (2, 4, 8, 8),
                    'window_sizes': (512, 256, 128, 64),
                    'down_ratios': (4, 4, 4),
                    'cond_dim': 2,
                    'num_routes': 1,
                    'mlp_ratio': 4.0,
                    'drop_path_rate': 0.0,
                    'proj_drop': 0.0,
                    'attn_drop': 0.0,
                    'use_flow_attention': True,
                    'use_flow_ffn': False},
 'decoder_name': 'CrossAttentionDecoder',
 'decoder_kwargs': {'out_channels': 4,
                    'query_dim': None,
                    'cond_dim': 2,
                    'num_routes': 1,
                    'query_in_dim': 4,
                    'mlp_ratio': 4.0,
                    'drop_path_rate': 0.0,
                    'proj_drop': 0.0,
                    'attn_drop': 0.0,
                    'use_flow_ffn': False,
                    'depth': 4,
                    'num_heads': 8,
                    'use_flow_attention': True},
 'default_query_chunk_size': 50000}
